FROM ubuntu:latest
RUN apt-get update -y && apt-get install -y apache2
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
VOLUME ["/var/log/apache2"]
EXPOSE 80
CMD /usr/sbin/apache2ctl -D FOREGROUND
